/**
 * Byte-for-byte reproductions of the verified wire examples in
 * .notes/wyoming-protocol.md §4 — generated by running the reference
 * implementation's own write_event() (rhasspy/wyoming 1.10.0).
 *
 * Our encoder is asserted for SEMANTIC equality plus exact byte lengths
 * (JSON key order / whitespace intentionally not required); the reference
 * bytes are asserted to decode exactly.
 */

import { describe, expect, it } from "vitest";
import {
  AudioChunk,
  Describe,
  parseAudioChunk,
  parseInfo,
  Synthesize,
} from "../src/protocol/events.js";
import { encodeEvent, EventDecoder } from "../src/protocol/framing.js";

// Example 1: describe request (header-only), 42 bytes including the newline.
const DESCRIBE_WIRE = Buffer.from(
  '{"type": "describe", "version": "1.10.0"}\n',
  "utf8",
);

// Example 2: audio-chunk, 16 kHz / 16-bit / mono, timestamp 0, 4-byte payload.
const AUDIO_CHUNK_DATA =
  '{"rate": 16000, "width": 2, "channels": 1, "timestamp": 0}';
const AUDIO_CHUNK_WIRE = Buffer.concat([
  Buffer.from(
    '{"type": "audio-chunk", "version": "1.10.0", "data_length": 58, "payload_length": 4}\n',
    "utf8",
  ),
  Buffer.from(AUDIO_CHUNK_DATA, "utf8"),
  Buffer.from([0x01, 0x02, 0x03, 0x04]),
]);

// Example 3: info response (abbreviated, single ASR program), data_length 629.
const INFO_DATA =
  '{"asr": [{"name": "faster-whisper", "attribution": {"name": "Guillaume Klein", "url": "https://github.com/guillaumekln/faster-whisper/"}, "installed": true, "description": "Faster Whisper", "version": "2.6.0", "models": [{"name": "tiny-int8", "attribution": {"name": "Systran", "url": "https://huggingface.co/Systran"}, "installed": true, "description": "Tiny model", "version": null, "languages": ["en"]}], "supports_transcript_streaming": false, "requires_external_vad": true, "prefers_auto_gain_enabled": true, "prefers_noise_reduction_enabled": true}], "tts": [], "handle": [], "intent": [], "wake": [], "mic": [], "snd": []}';
const INFO_WIRE = Buffer.concat([
  Buffer.from('{"type": "info", "version": "1.10.0", "data_length": 629}\n'),
  Buffer.from(INFO_DATA, "utf8"),
]);

// Example 4: synthesize with a named voice, data_length 66.
const SYNTHESIZE_DATA =
  '{"text": "Anchor alarm", "voice": {"name": "en_US-lessac-medium"}}';
const SYNTHESIZE_WIRE = Buffer.concat([
  Buffer.from(
    '{"type": "synthesize", "version": "1.10.0", "data_length": 66}\n',
  ),
  Buffer.from(SYNTHESIZE_DATA, "utf8"),
]);

describe("reference wire bytes decode exactly", () => {
  it("example 1: describe (42 bytes total)", () => {
    expect(DESCRIBE_WIRE.length).toBe(42);
    expect(new EventDecoder().feed(DESCRIBE_WIRE)).toEqual([
      { type: "describe", data: {} },
    ]);
  });

  it("example 2: audio-chunk with declared byte lengths", () => {
    expect(Buffer.byteLength(AUDIO_CHUNK_DATA, "utf8")).toBe(58);
    const events = new EventDecoder().feed(AUDIO_CHUNK_WIRE);
    expect(events).toHaveLength(1);
    const chunk = parseAudioChunk(events[0]!);
    expect(chunk).toEqual({
      rate: 16000,
      width: 2,
      channels: 1,
      timestamp: 0,
      audio: Buffer.from([1, 2, 3, 4]),
    });
  });

  it("example 3: info (629-byte data block)", () => {
    expect(Buffer.byteLength(INFO_DATA, "utf8")).toBe(629);
    const events = new EventDecoder().feed(INFO_WIRE);
    const info = parseInfo(events[0]!);
    expect(info?.asr).toHaveLength(1);
    expect(info?.asr[0]?.name).toBe("faster-whisper");
    expect(info?.asr[0]?.models?.[0]?.name).toBe("tiny-int8");
    expect(info?.asr[0]?.models?.[0]?.version).toBeNull();
    expect(info?.tts).toEqual([]);
    expect(info?.satellite).toBeUndefined();
  });

  it("example 4: synthesize with a named voice (66-byte data block)", () => {
    expect(Buffer.byteLength(SYNTHESIZE_DATA, "utf8")).toBe(66);
    const events = new EventDecoder().feed(SYNTHESIZE_WIRE);
    expect(events[0]?.data).toEqual({
      text: "Anchor alarm",
      voice: { name: "en_US-lessac-medium" },
    });
  });

  it("all four examples decode from one concatenated stream", () => {
    const wire = Buffer.concat([
      DESCRIBE_WIRE,
      AUDIO_CHUNK_WIRE,
      INFO_WIRE,
      SYNTHESIZE_WIRE,
    ]);
    const events = new EventDecoder().feed(wire);
    expect(events.map((e) => e.type)).toEqual([
      "describe",
      "audio-chunk",
      "info",
      "synthesize",
    ]);
  });
});

describe("our encodings are semantically equal with exact byte lengths", () => {
  it("describe: same header fields, header-only", () => {
    const wire = encodeEvent(Describe()).toString("utf8");
    const refHeader = JSON.parse(DESCRIBE_WIRE.toString("utf8"));
    expect(JSON.parse(wire.slice(0, -1))).toEqual(refHeader);
    expect(wire.indexOf("\n")).toBe(wire.length - 1);
  });

  it("audio-chunk: declared lengths match the encoded blocks exactly", () => {
    const wire = encodeEvent(
      AudioChunk(
        { rate: 16000, width: 2, channels: 1 },
        Buffer.from([1, 2, 3, 4]),
        0,
      ),
    );
    const newline = wire.indexOf(0x0a);
    const header = JSON.parse(wire.subarray(0, newline).toString("utf8"));
    expect(header.type).toBe("audio-chunk");
    expect(header.payload_length).toBe(4);
    const data = wire.subarray(newline + 1, newline + 1 + header.data_length);
    expect(JSON.parse(data.toString("utf8"))).toEqual(
      JSON.parse(AUDIO_CHUNK_DATA),
    );
    // payload begins immediately after the data block, no separators
    expect(wire.length).toBe(newline + 1 + header.data_length + 4);
    expect([...wire.subarray(wire.length - 4)]).toEqual([1, 2, 3, 4]);
  });

  it("synthesize: semantically identical data block", () => {
    const wire = encodeEvent(
      Synthesize("Anchor alarm", { voice: { name: "en_US-lessac-medium" } }),
    );
    const newline = wire.indexOf(0x0a);
    const header = JSON.parse(wire.subarray(0, newline).toString("utf8"));
    const data = wire.subarray(newline + 1);
    expect(data.length).toBe(header.data_length);
    expect(JSON.parse(data.toString("utf8"))).toEqual(
      JSON.parse(SYNTHESIZE_DATA),
    );
  });
});
